<a href="https://colab.research.google.com/github/AbhinavBanisetti/Tensorflow/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  I am going to learn Fundamental concepts of "Tensors" using Tensorflow


### Intoduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of tensor (ndim stands for no.of dimensions)
scalar.ndim

0

In [4]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Checking the Dimension of our Vector
vector.ndim

1

In [6]:
# Create a Matrix (has more than 1 dimension)
matrix= tf.constant([[45,18],
                     [75,35]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[45, 18],
       [75, 35]], dtype=int32)>

In [7]:
# Checking the Dimensions of matrix
matrix.ndim

2

In [10]:
# Create another matrix
another_matrix=tf.constant([[5,2],
                           [8,9]],dtype=tf.float16) # specify the data type with the dtype parameter
another_matrix                           

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[5., 2.],
       [8., 9.]], dtype=float16)>

In [11]:
# Whats the number of dimensions of another_matrix?
another_matrix.ndim 

2

In [12]:
# Let's create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                    [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# Dimension of tensor
tensor.ndim

3




### What we have created so far
* Scalar: A single Number
* Vector: Number with a Direction (ex: Wind speed and direction)
* Matrix: A 2-D array of numbers
* Tensor: an n Dimensional array of numbers (when n can be any number)



### Creating tensors with `tf.Variable`

In [17]:
# Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# Lets try changing one of the elements in our changable tensor
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [19]:
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [20]:
# How about we try .assign() to change the values
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
# Lets try changing the value in unchangeable_tensor
unchangeable_tensor[0]
unchangeable_tensor[0]=7

TypeError: ignored

In [24]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored