##  I am going to learn Fundamental concepts of "Tensors" using Tensorflow


### Intoduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of tensor (ndim stands for no.of dimensions)
scalar.ndim

0

In [ ]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Checking the Dimension of our Vector
vector.ndim

1

In [ ]:
# Create a Matrix (has more than 1 dimension)
matrix= tf.constant([[45,18],
                     [75,35]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[45, 18],
       [75, 35]], dtype=int32)>

In [ ]:
# Checking the Dimensions of matrix
matrix.ndim

2